type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start:
      type: "start"
      parameters:
        componentName: "Start"
    AI Prompt (Deprecated):
      type: "ai-prompt"
      parameters:
        componentName: "AI Prompt (Deprecated)"
        service:
          provider: "OpenAI"
          openAI:
            model:
            apiKey:
            temperature: "1"
            topP: "1"
            "n": "1"
            maxTokens:
        source:
          snowflake:
            database: "[Environment Default]"
            schema: "[Environment Default]"
            table:
            keyColumn:
            limit: "1000"
        promptContext:
          userContext:
          inputs:
          outputFormat: "TEXT"
        ragConfig:
          isRagEnabled: "No"
          pinecone:
            pineconeApiKey:
            pineconeEnvironment:
            pineconeProject:
            pineconeIndex:
            pineconeNamespace:
            topK: "3"
          lookupSource:
            dataLookupStrategy: "tableFromMetadata"
        destination:
          snowflake:
            database: "[Environment Default]"
            schema: "[Environment Default]"
            table:
            createTableOptions: "Fail if Table Exists"
design:
  components:
    Start:
      position:
        x: 0
        "y": 0
      tempMetlId: 1
    AI Prompt (Deprecated):
      position:
        x: 130
        "y": -120
      tempMetlId: 2
